apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: devconf2024-application-01
    app.kubernetes.io/instance: devconf2024-application-01
  name: devconf2024-application-01
  namespace: devconf2024-application-01
spec:
  ports:
  - name: 8001-tcp
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app.kubernetes.io/component: devconf2024-application-01
    app.kubernetes.io/instance: devconf2024-application-01
status:
  loadBalancer: {}
