---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-app
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: rhte2023-placement03
      requeueAfterSeconds: 180
  template:
    metadata:
      name: spring-app-{{name}}
    spec:
      destination:
        namespace: spring-apps-prod
        server: '{{server}}'
      project: default
      source:
        path: deploy/kustomize/overlays/prod
        repoURL: https://github.com/kskels/spring-app.git
        targetRevision: main
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
