---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: rhte2023-placement02
  namespace: openshift-gitops
spec:
  clusterSets:
    - rhte2023-gitops-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: gitops-cluster
              operator: In
              values:
                - "true"
