---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhte2023-application
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: rhte2023-gitops-clusters
      requeueAfterSeconds: 180
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
      name: rhte2023-application-{{name}}
    spec:
      destination:
        namespace: rhte2023-application
        server: '{{server}}'
      project: default
      source:
        path: rhte2023/04_deploy_applications/rhte2023-application
        repoURL: https://github.com/xbryan1/rhte-2023-acm-apps.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
