apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-app
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: devconf2024-gitops-clusters
        requeueAfterSeconds: 180
  template:
    metadata:
      name: argo-app-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/xbryan1/devconf-2024-acm-apps.git
        targetRevision: main
        path: devconf2024/04_deploy_applications/config/argocd
      destination:
        namespace: openshift-gitops
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
