kind: ConfigMap
apiVersion: v1
metadata:
  name: application-properties
  namespace: rhte2023-app03
data:
  application.properties: |-

    application.name=@project.artifactId@
    build.version=@project.version@
    build.timestamp=@timestamp@
