---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: spring-app-placement
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          gitops-cluster: "true"
