kind: Service
apiVersion: v1
metadata:
  name: devconf2024-application-03
  namespace: devconf2024-application-03
  labels:
    app: devconf2024-application-03
    app.kubernetes.io/component: devconf2024-application-03
    app.kubernetes.io/instance: devconf2024-application-03
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/component: devconf2024-application-03
    app.kubernetes.io/instance: devconf2024-application-03
