apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devconf2024-application-03-hpa
  namespace: devconf2024-application-03
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devconf2024-application-03
  targetCPUUtilizationPercentage: 30
